# Generated by Django 4.2 on 2024-05-30 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Capacitacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('puesto', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('fecha_vencimiento', models.DateField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('completada', 'Completada')], max_length=50)),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appgestion.personal')),
            ],
        ),
        migrations.CreateModel(
            name='RecordatorioDeTarea',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('fecha_recordatorio', models.DateTimeField()),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appgestion.personal')),
            ],
        ),
        migrations.CreateModel(
            name='CapacitacionPersonal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_asignacion', models.DateField(auto_now_add=True)),
                ('capacitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appgestion.capacitacion')),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appgestion.personal')),
            ],
        ),
        migrations.AddField(
            model_name='capacitacion',
            name='personal',
            field=models.ManyToManyField(through='appgestion.CapacitacionPersonal', to='appgestion.personal'),
        ),
    ]
