# Generated by Django 4.2 on 2024-05-30 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appgestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='capacitacion',
            name='fecha_realizacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='capacitacion',
            name='realizada',
            field=models.BooleanField(default=False),
        ),
    ]
