# Generated by Django 5.2 on 2026-01-04 00:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Operario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_crontareas.area')),
            ],
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarea_asignada', models.CharField(max_length=255)),
                ('fecha_ejecucion', models.DateField()),
                ('fecha_limite', models.DateField()),
                ('fecha_finalizacion', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('EN_PROCESO', 'En Proceso'), ('FINALIZADA', 'Finalizada')], default='EN_PROCESO', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_crontareas.operario')),
            ],
        ),
        migrations.CreateModel(
            name='ArchivoAdjunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='tareas/')),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='app_crontareas.tarea')),
            ],
        ),
    ]
