# Generated by Django 5.2 on 2025-12-09 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reclamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('tipo', models.CharField(choices=[('FORMAL', 'Formal'), ('NO_FORMAL', 'No Formal')], max_length=20)),
                ('codigo', models.CharField(max_length=100)),
                ('cliente', models.CharField(max_length=200)),
                ('destinatario', models.CharField(choices=[('BLANCHED', 'Blanched'), ('SUPER_CLEAN', 'Super Clean'), ('LOGISTICA', 'Logística'), ('CRUDO', 'Crudo'), ('TOSTADO', 'Tostado'), ('PASTA', 'Pasta')], max_length=50)),
                ('lote_reclamado', models.CharField(max_length=100)),
                ('motivo', models.CharField(max_length=200)),
                ('descripcion_reclamo', models.TextField()),
                ('gravedad', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta')], max_length=10)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('archivo_adjunto', models.FileField(blank=True, null=True, upload_to='reclamos_adjuntos/')),
                ('estado', models.CharField(choices=[('ABIERTO', 'Abierto'), ('CERRADO', 'Cerrado')], max_length=20)),
                ('año_lote_reclamado', models.IntegerField()),
            ],
        ),
    ]
