# Generated by Django 5.2 on 2025-12-10 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appreclamos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reclamo',
            name='motivo',
            field=models.CharField(choices=[('CE', 'CE'), ('CALIDAD', 'Calidad'), ('ENVASES', 'Envases'), ('INSECTOS', 'Insectos'), ('CARGA', 'Carga'), ('ETIQUETADO', 'Etiquetado')], max_length=50),
        ),
    ]
