# Generated by Django 5.2 on 2025-12-10 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appreclamos', '0002_alter_reclamo_motivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reclamo',
            name='motivo',
            field=models.CharField(max_length=200),
        ),
    ]
