# Generated by Django 5.2.8 on 2025-11-27 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Capacitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('operario', models.CharField(max_length=100)),
                ('sector', models.CharField(max_length=100)),
                ('nombre_capacitacion', models.CharField(max_length=200)),
                ('dictado', models.CharField(choices=[('insitu', 'In Situ'), ('classroom', 'Classroom')], max_length=10)),
                ('nota', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
