# Generated by Django 5.2.8 on 2025-11-30 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='capacitacion',
            name='quien_realizo',
            field=models.CharField(default='Desconocido', max_length=150),
            preserve_default=False,
        ),
    ]
